### ISSUE TITLE
Use PerformanceTiming API to measure response time

### ISSUE THREAD

**Issue by yuryu** [GoogleCloudPlatform/gcping#55] opened 2021-09-09 21:27 UTC
There's a web API to get the exact duration for each http request, which is more accurate than using Date and you can remove DNS lookup times.

https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API

**Comment by enocom** [comment] 2021-09-09 21:30
Very cool. Thanks for idea @yuryu.

**Comment by enocom** [comment] 2021-09-13 22:01
Going to close this as a duplicate of #27.

**Closed by enocom** 2021-09-13 22:01 UTC
